name: react/metro/labeler
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  labeler:
    if: github.repository == 'react/metro'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v7
